### ISSUE TITLE
volumeBindingMode modify avaliable?

### ISSUE THREAD

**Issue by centrair-hoya** [nutanix/helm#84]
Hi, Nutanixers.

On acs-abs/afs, volumeBindingMode is Immediate by default.

We will deploy IBM API GATEWAY on Redhat Openshift, IBM require volumeBindingMode changed 'Immediate' to 'WaitForFirstConsumer'
( https://www.ibm.com/docs/en/api-connect/10.0.1.x?topic=connect-deployment-requirements ) 

Is there any problem to CSI Driver or Nutanix Files/Volumes if change volumeBindingMode?

Thank you.

**Comment by tuxtof** [comment]
Hi @centrair-hoya 

There is no problem to use the `volumeBindingMode: WaitForFirstConsumer` setting.

But it is a little bit useless for the moment because the CSI driver is only targeting a single cluster , and every nodes in the cluster is able to access the storage through the distributed storage layer.

In the future we plan to implement multi cluster support and in this case zone/topology support, when it will be available it will make more sense to change the volumeBindingMode

Take care
